//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalleryCafeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactID { get; set; }
        public string ConName { get; set; }
        public string ConEmail { get; set; }
        public Nullable<int> ConPhone { get; set; }
        public string ConSubject { get; set; }
        public string ConMessage { get; set; }
    }
}
