//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalleryCafeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public int CustomerID { get; set; }
        public string ResName { get; set; }
        public string ResEmail { get; set; }
        public int ResPhoneNumber { get; set; }
        public string ResDate { get; set; }
        public string ResTime { get; set; }
        public string ResMessage { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
